spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/eeum}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

server:
  port: ${SERVER_PORT:8080}

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: ${JWT_ACCESS_EXPIRATION:1800}
  refresh-token-expiration: ${JWT_REFRESH_EXPIRATION:1209600}
  reauth-token-expiration: ${JWT_REAUTH_TOKEN_EXPIRATION:300}
  password-reset-token-expiration: ${JWT_PASSWORD_RESET_TOKEN_EXPIRATION:1800}

auth:
  email-verification-code-expiration: ${EMAIL_VERIFICATION_CODE_EXPIRATION:300}
  email-verification-token-expiration: ${EMAIL_VERIFICATION_TOKEN_EXPIRATION:1800}

business:
  nts:
    service-key: ${NTS_BUSINESS_SERVICE_KEY}